# `180280116118` Ishika Tailor

# **AIM: Exploring Numpy library to perform various tasks for array handling, wrangling, cleaning,description,arrangement.**

In [1]:
import numpy as np
import pandas as pd

In [2]:
print('1D array with 15 elements:\n', np.array([1, 2, 3,4,5,6,7,8,9,10,11,12,13,14,15]))
print('2D array:6*6\n', np.array([[1, 2, 3,4, 5, 6],[1, 2, 3,4, 5, 6],[1, 2, 3,4, 5, 6],[1, 2, 3,4, 5, 6],[1, 2, 3,4, 5, 6],[1, 2, 3,4, 5, 6]]))

1D array with 15 elements:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
2D array:6*6
 [[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [3]:
a=np.array([1, 2, 3,4,5,6,7,8,9,10,11,12,13,14,15])
b=np.array([[1, 2, 3,4, 5, 6],
            [1, 2, 3,4, 5, 6],
            [1, 2, 3,4, 5, 6],
            [1, 2, 3,4, 5, 6],
            [1, 2, 3,4, 5, 6],
            [1, 2, 3,4, 5, 6]])
a.dtype

dtype('int64')

In [4]:
b.dtype

dtype('int64')

**[1] Create a 6x6 integer array and Prints its attributes.
The element must be a type of unsigned int16.
And print the following Attributes: – The shape of an array. Array dimensions. The Length of each element of the array in bytes.**

In [5]:
Array = np.empty([6,6], dtype = np.uint16) 

In [6]:
print("Printing numpy array Attributes")
print("1) Array Shape is: ", Array.shape)
print("2) Array dimensions are ", Array.ndim)
print("3) Length of each element of array in bytes is ", Array.itemsize)

Printing numpy array Attributes
1) Array Shape is:  (6, 6)
2) Array dimensions are  2
3) Length of each element of array in bytes is  2


In [7]:
#Dimention of array
print(a.ndim,b.ndim)

1 2


In [8]:
#Shape of array
print(a.shape,b.shape)

(15,) (6, 6)


In [9]:
#Total bytes consumed by the elements of the array
print(a.nbytes,b.nbytes)

120 288


In [10]:
#length of one array element in bytes
print(a.itemsize,b.itemsize)

8 8


**[2]Create a null vector of size 10**

In [11]:
#Creating Null array of size 10
c=np.zeros(shape=(10,))
print(np.zeros(shape=(10,)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
c.size

10

**[3]Create a vector with values ranging from 10 to 49**

In [13]:
d=np.arange(10,49)
print("Original vector:",d)
print("All value except first and last:",d[1:-1])

Original vector: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
All value except first and last: [11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47]


**[4]Reverse a vector (first element becomes last)**

In [14]:
print("Reverse vector:",d[::-1])

Reverse vector: [48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


**[5]Find indices of non-zero elements from [1,2,0,0,4,0]**

In [15]:
#Find indices of non-zero element[1,2,0,0,4,0]
print(np.nonzero([1,2,0,0,4,0]))

(array([0, 1, 4]),)


`0,1,4 are indices of non-zero array`

**[6]Create a 6X6 integer array from a range between 100 to 200 such that the difference between each element is 10**

In [16]:
print("Creating 6X6 array using numpy.arange but element is less for creating 6X6 array.  ")
print("So, i have created 5X2 array")
g = np.arange(100, 200, 10)
g = g.reshape(5,2)
print (g)

Creating 6X6 array using numpy.arange but element is less for creating 6X6 array.  
So, i have created 5X2 array
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


**[7]Given 6x6 numPy array. return array of items in the third column from all rows**

In [17]:
print("Printing Input Array")
print(b)

print("\n Printing array of items in the third column from all rows")
output = b[...,2]
print(output)

Printing Input Array
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]

 Printing array of items in the third column from all rows
[3 3 3 3 3 3]


**[8]Given 6x6 numpy array return array of odd rows and even columns**

In [18]:
h=np.array([[1, 2, 3,4, 5, 6],
            [1, 2, 3,8, 5, 6],
            [1, 2, 3,4, 5, 6],
            [1, 2, 3,8, 5, 6],
            [1, 2, 3,4, 5, 6],
            [1, 2, 3,9, 5, 6]])
print("\n Printing array of odd rows and even columns")
OddEven = h[::2, 1::2]
print(OddEven)


 Printing array of odd rows and even columns
[[2 4 6]
 [2 4 6]
 [2 4 6]]


**[9]Add the following two NumPy arrays and Modify a result array by calculating the square of each element**

In [19]:
arr1 = np.array([[5, 6, 9], [2 ,8, 7]])
arr2 = np.array([[5 ,3, 2], [4 ,7, 1]])

result  = arr1 + arr2
print("addition of two arrays is \n")
print(result)

for num in np.nditer(result, op_flags = ['readwrite']):
   num[...] = num*num
print("\nResult array after calculating the square root of all elements\n")
print(result)

addition of two arrays is 

[[10  9 11]
 [ 6 15  8]]

Result array after calculating the square root of all elements

[[100  81 121]
 [ 36 225  64]]


**[10]Split the array into four equal-sized sub-arrays**

In [20]:
array = np.arange(1, 25, 1)
i = array.reshape(8,3)
print (i)

print("\nDividing 8X3 array into 4 sub array\n")
subarray = np.split(i, 4) 
print(subarray)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]]

Dividing 8X3 array into 4 sub array

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]]), array([[19, 20, 21],
       [22, 23, 24]])]


**[11] Sort following NumPy array**

In [21]:
print("Printing Original array")
j = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (j)

sortArrayByRow = j[:,j[0,:].argsort()]
print("Sorting Original array by first row")
print(sortArrayByRow)

sortArrayByRow = j[:,j[1,:].argsort()]
print("Sorting Original array by secoond row")
print(sortArrayByRow)

print("Sorting Original array by first column")
sortArrayByColumn = j[j[:,0].argsort()]
print(sortArrayByColumn)

print("Sorting Original array by secoond column")
sortArrayByColumn = j[j[:,1].argsort()]
print(sortArrayByColumn)

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Sorting Original array by first row
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Sorting Original array by secoond row
[[73 43 34]
 [12 22 82]
 [66 94 53]]
Sorting Original array by first column
[[34 43 73]
 [53 94 66]
 [82 22 12]]
Sorting Original array by secoond column
[[82 22 12]
 [34 43 73]
 [53 94 66]]


**[12] Given 6x6 NumPy Array, Print max from axis 0 and min from axis 1**

In [22]:
minOfAxisOne = np.amin(j, 1) 
print("Printing amin Of Axis 1")
#Checking minimum element row by row
print(minOfAxisOne)

maxOfAxisOne = np.amax(j, 0) 
print("Printing amax Of Axis 0")
#checking maximum element column by column
print(maxOfAxisOne)

Printing amin Of Axis 1
[34 12 53]
Printing amax Of Axis 0
[82 94 73]


**[13] G Given 6x6 input NumPy array delete column two and insert following new column in its place.**

In [23]:
print("Array after deleting column 2 on axis 1")
d1 = np.delete(i , 1, axis = 1) 
print (d1)

arr = np.array([[1,2,3,4,5,6,7,8]])

print("Array after inserting column 2 on axis 1")
d2 = np.insert(i , 1, arr, axis = 1) 
print (d2)

Array after deleting column 2 on axis 1
[[ 1  3]
 [ 4  6]
 [ 7  9]
 [10 12]
 [13 15]
 [16 18]
 [19 21]
 [22 24]]
Array after inserting column 2 on axis 1
[[ 1  1  2  3]
 [ 4  2  5  6]
 [ 7  3  8  9]
 [10  4 11 12]
 [13  5 14 15]
 [16  6 17 18]
 [19  7 20 21]
 [22  8 23 24]]


**[14] Create a boolean array with all values True.**

In [24]:
bool_arr=np.ones(5,dtype=bool)
bool_arr

array([ True,  True,  True,  True,  True])

**[15] Replace items that satisfy a condition with another value in numpy array**

In [25]:
# Call numpy.where(condition,x,y) to replace values that meet condition with x
print(i)
arr_replace=np.where(i>15,0,i)
print("After replacing:")
arr_replace

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]]
After replacing:


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0]])

**[16] Compute the moving average of a numpy array**

In [26]:
# There seems to be no function that simply calculates the moving average on numpy. 
#But we can easily implement it with np.cumsum
# EX: [1,1,1,1] array=[5,3,8,10,2,1] w=4
# =(1*5+1*3+1*8+1*10)/w  =6.5
# =(1*3+1*8+1*10+1*2)/w  =5.75 and so on.
def moving_average(a,w):
       for m in range(len(a)-(w-1)):
        yield sum(np.ones(w)* a[m:m+w])/w

a=np.array([5, 3, 8, 10, 2, 1, 5, 1, 0, 2])
print("a:",a)
list(moving_average(a,4))

a: [ 5  3  8 10  2  1  5  1  0  2]


[6.5, 5.75, 5.25, 4.5, 2.25, 1.75, 2.0]